--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25.04.2021 18:27:47
-- Server version: 5.5.5-10.1.37-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE immersion;

--
-- Drop table `groups`
--
DROP TABLE IF EXISTS groups;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `user_sessions`
--
DROP TABLE IF EXISTS user_sessions;

--
-- Set default database
--
USE immersion;

--
-- Create table `user_sessions`
--
CREATE TABLE user_sessions (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id int(11) UNSIGNED DEFAULT NULL,
  hash varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  pic varchar(255) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  job varchar(255) DEFAULT NULL,
  vk varchar(255) DEFAULT NULL,
  telegram varchar(255) DEFAULT NULL,
  status char(20) DEFAULT NULL,
  tel varchar(255) DEFAULT NULL,
  group_id tinyint(4) UNSIGNED DEFAULT 1,
  email varchar(50) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  instagram varchar(255) DEFAULT NULL,
  adress varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 33,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `text` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX text (tel);

--
-- Create table `groups`
--
CREATE TABLE groups (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  permissions varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table user_sessions
--
INSERT INTO user_sessions VALUES
(4, 32, '24b3c693ec6a52a2dfdd182fa07586bc99576df1e5df8b4c0baed8c47d321389');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, '', 'Oliver Kopyov', 'IT Director, Gotbootstrap Inc.', '', '', 'success', '+1 317-456-2564', 1, 'oliver.kopyov@smartadminwebapp.com', '$2y$10$qMDigZfCG9aZbiUKG5rTWuTCl4V9jQ5erQM/CRv35GIlrWby6aw2y', '', '15 Charist St, Detroit, MI, 48212, USA'),
(3, 'avatar-e', 'Dr. John Cook PhD', 'Human Resources, Gotbootstrap Inc.', '', '', 'danger', '+1 313-779-1347', 1, 'sdfd@dsff.bbb', '$2y$10$ESRMn6wXHGOp/II80Z8AHuu.lKocT2x/Yl5.x1ZdVcEbV4M2s9C9i', '', '55 Smyth Rd, Detroit, MI, 48341, USA'),
(4, 'avatar-k', 'Jim Ketty', 'Staff Orgnizer, Gotbootstrap Inc.', '', '', 'success', '+1 313-779-3314', 1, 'jim.ketty@smartadminwebapp.com', '$2y$10$Pp9sQgbbX2cGYZfY8sK2su1.VI6ZXduhp/MQXCLuGPSwcj1uGJrFW', '', '134 Tasy Rd, Detroit, MI, 48212, USA'),
(5, 'avatar-g', 'Dr. John Oliver', 'Oncologist, Gotbootstrap Inc.', '', '', 'success', ' john.oliver@smartadminwebapp.com', 1, 'john.oliver@smartadminwebapp.com', '$2y$10$p6oGF9UJJ4FcHALqkzT6MuFScuVATv9.sRQOV5axP8soHLKu2eviO', '', '134 Gallery St, Detroit, MI, 46214, USA'),
(6, 'avatar-h', 'Sarah McBrook', 'Xray Division, Gotbootstrap Inc.', '', '', 'success', '+1 313-779-7613', 1, 'sarah.mcbrook@smartadminwebapp.com', '$2y$10$z6Y5sU8k1.UDgUivv6MsD.cFvh08G6Q27wA5yb59j1HjWJYmmcL2G', '', '13 Jamie Rd, Detroit, MI, 48313, USA'),
(7, 'avatar-i', 'Jimmy Fellan', 'Accounting, Gotbootstrap Inc.', '', '', 'success', '+1 313-779-4314', 1, 'jimmy.fallan@smartadminwebapp.com', '$2y$10$wRMGc.I06DibGz0ZyD1HJOXX.POvK8k7Q8q4yKcqizMEq7TcW.Uf2', '', '55 Smyth Rd, Detroit, MI, 48341, USA'),
(8, 'avatar-j', 'Arica Grace', 'Accounting, Gotbootstrap Inc.', '', '', 'success', '+1 313-779-3347', 1, 'arica.grace@smartadminwebapp.com', '$2y$10$CKgWLTgAnr/QITfTwK9DQ./lCXm.zDL7LO0J4qmhSzMoR/1cP19wO', '', '798 Smyth Rd, Detroit, MI, 48341, USA'),
(32, NULL, 'bbb', NULL, NULL, NULL, NULL, NULL, 2, 'aaa@aa.aa', '$2y$10$4SGhZhZoeRgncm7yZ4P8ueJYPUT1/.doypIPkjTxBVKtSx6uVNlye', NULL, NULL);

-- 
-- Dumping data for table groups
--
INSERT INTO groups VALUES
(1, 'Standart User', NULL),
(2, 'Administrator', '{"admin":1, "moderator":2}');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;